#!/bin/bash
export LD_LIBRARY_PATH=/THFS/opt/intel/composer_xe_2013_sp1.3.174/mkl/lib/intel64:/THFS/opt/intel/composer_xe_2013_sp1.3.174/compiler/lib/intel64:$LD_LIBRARY_PATH
yhrun -p gscomp -N 1 -n 24 /THFS/opt/vasp/5.3.5/vasp.5.3/vasp
